import React, { useState, useEffect } from 'react';
import { FaPlane, FaRoute, FaWallet, FaClock, FaTrash, FaFilePdf, FaArrowLeft } from 'react-icons/fa';
import { tripAPI } from '../../services/api';
import Navbar from '../Common/Navbar';
import './TripHistory.css';

const TripHistory = ({ user, onLogout }) => {
  const [trips, setTrips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [deleting, setDeleting] = useState(null);

  useEffect(() => {
    loadTrips();
  }, []);

  const loadTrips = async () => {
    try {
      const response = await tripAPI.getAll();
      setTrips(response.data.trips);
    } catch (error) {
      setError('Failed to load trip history');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (tripId) => {
    if (!window.confirm('Are you sure you want to delete this trip?')) {
      return;
    }

    setDeleting(tripId);
    try {
      await tripAPI.delete(tripId);
      setTrips(trips.filter(trip => trip.trip_id !== tripId));
    } catch (error) {
      setError('Failed to delete trip');
      console.error(error);
    } finally {
      setDeleting(null);
    }
  };

  const exportToPDF = (trip) => {
    // Simple PDF export using browser print functionality
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Trip Details - ${trip.source_name} to ${trip.dest_name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #667eea; margin-bottom: 20px; }
            .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .detail { margin: 10px 0; }
            .badge { background: #667eea; color: white; padding: 8px 16px; border-radius: 4px; display: inline-block; margin: 10px 0; }
          </style>
        </head>
        <body>
          <h1>Trip Details</h1>
          <div class="header">
            <div>
              <p><strong>Date:</strong> ${new Date(trip.created_at).toLocaleDateString()}</p>
            </div>
          </div>
          <hr>
          <h2>Route</h2>
          <p><strong>From:</strong> ${trip.source_name}, ${trip.source_city}, ${trip.source_state}</p>
          <p><strong>To:</strong> ${trip.dest_name}, ${trip.dest_city}, ${trip.dest_state}</p>
          <hr>
          <h2>Trip Summary</h2>
          <p><strong>Mode:</strong> <span class="badge">${trip.selected_mode}</span></p>
          <p><strong>Total Cost:</strong> ₹${trip.total_cost}</p>
          <p><strong>Duration:</strong> ${trip.total_duration} minutes</p>
          <p><strong>Comfort Level:</strong> ${trip.comfort_score}/10</p>
          <hr>
          <p style="margin-top: 40px; color: #666;">Generated by Travel Mitr</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (loading) {
    return (
      <>
        <Navbar user={user} onLogout={onLogout} />
        <div className="history-container">
          <div className="spinner" />
        </div>
      </>
    );
  }

  return (
    <>
      <Navbar user={user} onLogout={onLogout} />
      <div className="history-container">
        <div className="container">
          <div className="page-header">
            <h1><FaRoute /> Trip History</h1>
            <p>View and manage your saved travel plans</p>
          </div>

          {error && <div className="alert alert-error">{error}</div>}

          {trips.length === 0 ? (
            <div className="card">
              <div className="empty-state">
                <FaPlane className="empty-icon" />
                <h2>No trips yet</h2>
                <p>Start planning your first trip to see it here!</p>
              </div>
            </div>
          ) : (
            <div className="trips-grid">
              {trips.map(trip => (
                <div key={trip.trip_id} className="trip-card">
                  <div className="trip-header">
                    <div>
                      <h3>{trip.source_name} → {trip.dest_name}</h3>
                      <p className="trip-date">{new Date(trip.created_at).toLocaleString()}</p>
                    </div>
                    <div className="trip-actions">
                      <button
                        className="btn-icon"
                        onClick={() => exportToPDF(trip)}
                        title="Export to PDF"
                      >
                        <FaFilePdf />
                      </button>
                      <button
                        className="btn-icon btn-icon-danger"
                        onClick={() => handleDelete(trip.trip_id)}
                        disabled={deleting === trip.trip_id}
                        title="Delete trip"
                      >
                        {deleting === trip.trip_id ? <div className="mini-spinner" /> : <FaTrash />}
                      </button>
                    </div>
                  </div>

                  <div className="trip-details">
                    <div className="trip-detail-item">
                      <FaRoute className="detail-icon" />
                      <div>
                        <strong>Mode</strong>
                        <p>{trip.selected_mode}</p>
                      </div>
                    </div>

                    <div className="trip-detail-item">
                      <FaWallet className="detail-icon" />
                      <div>
                        <strong>Cost</strong>
                        <p>₹{trip.total_cost}</p>
                      </div>
                    </div>

                    <div className="trip-detail-item">
                      <FaClock className="detail-icon" />
                      <div>
                        <strong>Duration</strong>
                        <p>{trip.total_duration} min</p>
                      </div>
                    </div>
                  </div>

                  <div className="trip-locations">
                    <div className="location-item">
                      <strong>From:</strong> {trip.source_city}, {trip.source_state}
                    </div>
                    <div className="location-item">
                      <strong>To:</strong> {trip.dest_city}, {trip.dest_state}
                    </div>
                  </div>

                  <div className="comfort-score">
                    Comfort Score: {trip.comfort_score}/10
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default TripHistory;

